"""add request hash

Revision ID: 2415ca82021c
Revises: ea7950b06cc7
Create Date: 2026-08-20 22:57:33.134658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2415ca82021c'
down_revision: Union[str, Sequence[str], None] = 'ea7950b06cc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('payments', sa.Column('payment_id', sa.UUID(), nullable=False))
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_unique_constraint(None, 'payments', ['payment_id'])
    op.create_table('idempotency_keys',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('payment_id', sa.UUID(), nullable=False),
        sa.Column('idempotency_key', sa.String(), nullable=False),
        sa.Column('request_hash', sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('idempotency_key'),
        sa.UniqueConstraint('payment_id'),
        sa.UniqueConstraint('request_hash')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    op.alter_column('payments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('payments', 'payment_id')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###
