"""add payment status history

Revision ID: 87bb082e5874
Revises: cdd6e830a709
Create Date: 2026-08-29 16:21:00.323492

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87bb082e5874'
down_revision: Union[str, Sequence[str], None] = 'cdd6e830a709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('old_status', postgresql.ENUM('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='paymentstatus',create_type=False), nullable=False),
    sa.Column('new_status', postgresql.ENUM('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='paymentstatus',create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.payment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_status_history')
    # ### end Alembic commands ###
