"""changed table name User to user

Revision ID: c6e495c6207f
Revises: fb458c9daf96
Create Date: 2026-09-06 23:30:55.574547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6e495c6207f'
down_revision: Union[str, Sequence[str], None] = 'fb458c9daf96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('fk_payments_user_id'),
        'payments',
        type_='foreignkey'
    )

    op.rename_table('Users', 'users')

    op.create_foreign_key(
        'fk_payments_user_id',
        'payments',
        'users',
        ['user_id'],
        ['user_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('fk_payments_user_id'), 'payments', 'Users', ['user_id'], ['user_id'])
    op.create_table('Users',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('CUSTOMER', 'PAYMENTPROCESSOR', 'ADMIN', name='userroles'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('Users_pkey')),
    sa.UniqueConstraint('username', name=op.f('Users_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('users')
    # ### end Alembic commands ###
