"""removed unique constraint on idempotency_keys request hash key

Revision ID: cdd6e830a709
Revises: 2415ca82021c
Create Date: 2026-08-20 23:17:21.330363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd6e830a709'
down_revision: Union[str, Sequence[str], None] = '2415ca82021c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('idempotency_keys_request_hash_key'), 'idempotency_keys', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('idempotency_keys_request_hash_key'), 'idempotency_keys', ['request_hash'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
