"""updated model

Revision ID: e6c1d91ef91d
Revises: f98b2b851fa9
Create Date: 2026-09-23 14:56:23.940028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c1d91ef91d'
down_revision: Union[str, Sequence[str], None] = 'f98b2b851fa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('recipient_account_number', sa.String(length=12), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'recipient_account_number')
    # ### end Alembic commands ###
