"""changed currency datatype to enum

Revision ID: ea7950b06cc7
Revises: 
Create Date: 2026-08-18 22:52:21.470671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea7950b06cc7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('payments', 'currency',
#                existing_type=sa.VARCHAR(),
#                type_=sa.Enum('MYR', 'USD', 'SGD', name='currencies'),
#                existing_nullable=False)
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('payments', 'currency',
#                existing_type=sa.Enum('MYR', 'USD', 'SGD', name='currencies'),
#                type_=sa.VARCHAR(),
#                existing_nullable=False)
    # ### end Alembic commands ###

def upgrade() -> None:
    """Upgrade schema."""

    currencies = sa.Enum(
        'MYR',
        'USD',
        'SGD',
        name='currencies'
    )

    currencies.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        'payments',
        'currency',
        existing_type=sa.VARCHAR(),
        type_=currencies,
        existing_nullable=False,
        postgresql_using='currency::currencies'
    )


def downgrade() -> None:
    """Downgrade schema."""

    currencies = sa.Enum(
        'MYR',
        'USD',
        'SGD',
        name='currencies'
    )

    op.alter_column(
        'payments',
        'currency',
        existing_type=currencies,
        type_=sa.VARCHAR(),
        existing_nullable=False,
        postgresql_using='currency::text'
    )

    currencies.drop(op.get_bind(), checkfirst=True)