"""add account number

Revision ID: f98b2b851fa9
Revises: b08965b9ac76
Create Date: 2026-09-20 15:08:06.991192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f98b2b851fa9'
down_revision: Union[str, Sequence[str], None] = 'b08965b9ac76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_number', sa.String(length=12), nullable=False))
    op.create_unique_constraint(None, 'users', ['account_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'account_number')
    # ### end Alembic commands ###
