"""added user table for authentication

Revision ID: faf7ae88796d
Revises: 87bb082e5874
Create Date: 2026-09-06 22:27:47.993320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faf7ae88796d'
down_revision: Union[str, Sequence[str], None] = '87bb082e5874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', 'PAYMENTPROCESSOR', 'ADMIN', name='userroles'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.add_column('payments', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_column('payments', 'customer_id')
    op.create_foreign_key(
    'fk_payments_user_id',
    'payments',
    'Users',
    ['user_id'],
    ['user_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('payments', 'user_id')
    op.drop_table('Users')
    # ### end Alembic commands ###
